//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTS.Common.Resource.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi phát sinh trong quy trình xử lý!.
        /// </summary>
        public static string ERR0001 {
            get {
                return ResourceManager.GetString("ERR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại hoặc đã bị xóa! .
        /// </summary>
        public static string ERR0002 {
            get {
                return ResourceManager.GetString("ERR0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục không tồn tại hoặc đã bị xóa!.
        /// </summary>
        public static string ERR0003 {
            get {
                return ResourceManager.GetString("ERR0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để xuất. Vui lòng thử lại!.
        /// </summary>
        public static string ERR0004 {
            get {
                return ResourceManager.GetString("ERR0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại!.
        /// </summary>
        public static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên {0} đã tồn tại. Vui lòng nhập tên {0} khác!.
        /// </summary>
        public static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} đã tồn tại. Vui lòng nhập mã {0} khác!.
        /// </summary>
        public static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} này đang được sử dụng. Vui lòng xem lại!.
        /// </summary>
        public static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} này bạn không có quyền xem!.
        /// </summary>
        public static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} và {1} đều phải được chọn! Vui lòng xem lại!.
        /// </summary>
        public static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có file {0} nào!.
        /// </summary>
        public static string MSG0007 {
            get {
                return ResourceManager.GetString("MSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại hoặc đã bị xóa!.
        /// </summary>
        public static string MSG0008 {
            get {
                return ResourceManager.GetString("MSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng. Vui lòng nhập lại!.
        /// </summary>
        public static string MSG0009 {
            get {
                return ResourceManager.GetString("MSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có giá trị lớn hơn 0. Vui lòng nhập lại!.
        /// </summary>
        public static string MSG0010 {
            get {
                return ResourceManager.GetString("MSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trạng thái đã bị thay đổi. Bạn hãy kiểm tra lại!.
        /// </summary>
        public static string MSG0011 {
            get {
                return ResourceManager.GetString("MSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string MSG0012 {
            get {
                return ResourceManager.GetString("MSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không đúng.
        /// </summary>
        public static string MSG0013 {
            get {
                return ResourceManager.GetString("MSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống !.
        /// </summary>
        public static string MSG0014 {
            get {
                return ResourceManager.GetString("MSG0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không có trong hệ thống.
        /// </summary>
        public static string MSG0015 {
            get {
                return ResourceManager.GetString("MSG0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng!.
        /// </summary>
        public static string MSG0017 {
            get {
                return ResourceManager.GetString("MSG0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại. Bạn vui lòng nhập thông tin khác!.
        /// </summary>
        public static string MSG0018 {
            get {
                return ResourceManager.GetString("MSG0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới {0} thành công..
        /// </summary>
        public static string MSG0019 {
            get {
                return ResourceManager.GetString("MSG0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập {0} thành công..
        /// </summary>
        public static string MSG0020 {
            get {
                return ResourceManager.GetString("MSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không được trùng với mật khẩu cũ!.
        /// </summary>
        public static string MSG0021 {
            get {
                return ResourceManager.GetString("MSG0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu không thành công!.
        /// </summary>
        public static string MSG0022 {
            get {
                return ResourceManager.GetString("MSG0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được ít hơn 8 kí tự!.
        /// </summary>
        public static string MSG0023 {
            get {
                return ResourceManager.GetString("MSG0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được nhiều hơn 16 kí tự!.
        /// </summary>
        public static string MSG0024 {
            get {
                return ResourceManager.GetString("MSG0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải bao gồm chữ hoa, chữ thường, số, kí tự đặc biệt!.
        /// </summary>
        public static string MSG0025 {
            get {
                return ResourceManager.GetString("MSG0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thành công!.
        /// </summary>
        public static string MSG0026 {
            get {
                return ResourceManager.GetString("MSG0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload lỗi: File không có dung lượng.
        /// </summary>
        public static string MSG0027 {
            get {
                return ResourceManager.GetString("MSG0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng file {0} không được phép upload! .
        /// </summary>
        public static string MSG0028 {
            get {
                return ResourceManager.GetString("MSG0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bị khóa. Lên hệ quản trị để kích hoạt lại!.
        /// </summary>
        public static string MSG0029 {
            get {
                return ResourceManager.GetString("MSG0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có file download.
        /// </summary>
        public static string MSG0030 {
            get {
                return ResourceManager.GetString("MSG0030", resourceCulture);
            }
        }
    }
}
